name: app-build-ios-only

on:
  workflow_dispatch:

jobs:
  # 仅打包 iOS
  build-ios:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      # 签出代码（默认当前触发分支）
      - uses: actions/checkout@v4

      # 设置 JAVA 环境（Flutter 构建依赖）
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      # 设置 Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      # 更新 Flutter 的 packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # 打包 iOS
      - name: Build IPA (no codesign)
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      # 创建未签名 IPA
      - name: Create IPA
        run: |
          cd simple_live_app
          mkdir -p build/ios/iphoneos/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos/
          zip -q -r ios_no_sign.ipa Payload
          cd ../../..

      # 上传 IPA 至 Artifacts
      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: |
            simple_live_app/build/ios/iphoneos/ios_no_sign.ipa

      # 完成
      - run: echo "🍏 iOS-only job's status is ${{ job.status }}."

