name: app-build-ios-macos

on:
  workflow_dispatch:

jobs:
  # 打包 iOS 和 macOS
  build-ios-macos:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      # 签出当前触发工作流的分支/提交
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      # 设置 JAVA 环境
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      # 设置 Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      # 打开 MAC Desktop 支持
      - name: Enable Flutter Desktop
        run: flutter config --enable-macos-desktop

      # 更新 Flutter 的 packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # 安装 appdmg
      - name: Install appdmg
        run: npm install -g appdmg

      # 设置 flutter_distributor 环境
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      # 将 Dart 全局可执行目录加入 PATH，供后续 flutter_distributor 使用
      - name: Add Dart pub cache to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      # 打包 iOS
      - name: Build IPA (no codesign)
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      # 创建未签名 IPA
      - name: Create IPA
        run: |
          cd simple_live_app
          mkdir -p build/ios/iphoneos/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos/
          zip -q -r ios_no_sign.ipa Payload
          cd ../../..

      # 上传 IPA 至 Artifacts
      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: |
            simple_live_app/build/ios/iphoneos/ios_no_sign.ipa

      # 打包 macOS
      - name: Build MacOS
        run: |
          cd simple_live_app
          flutter_distributor package --platform macos --targets dmg,zip --skip-clean

      # 上传 macOS 至 Artifacts
      - name: Upload MacOS to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: |
            simple_live_app/build/dist/*/*.dmg
            simple_live_app/build/dist/*/*.zip

      # 完成
      - run: echo "🍏 iOS + macOS job's status is ${{ job.status }}."
